apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  capacity: 
   storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /c/Users/ASUS/Downloads/k8s/cicd_jenkins/jenkins-k8s-yaml/jenkins-data

